/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './easy-ngx-google-analytics.component';
import * as i2 from '@angular/router';
const styles_EasyNgxGoogleAnalyticsComponent:any[] = ([] as any[]);
export const RenderType_EasyNgxGoogleAnalyticsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_EasyNgxGoogleAnalyticsComponent,data:{}});
export function View_EasyNgxGoogleAnalyticsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_EasyNgxGoogleAnalyticsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'easy-ngx-google-analytics',
      ([] as any[]),(null as any),(null as any),(null as any),View_EasyNgxGoogleAnalyticsComponent_0,
      RenderType_EasyNgxGoogleAnalyticsComponent)),i0.ɵdid(1,49152,(null as any),0,
      i1.EasyNgxGoogleAnalyticsComponent,[i2.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const EasyNgxGoogleAnalyticsComponentNgFactory:i0.ComponentFactory<i1.EasyNgxGoogleAnalyticsComponent> = i0.ɵccf('easy-ngx-google-analytics',
    i1.EasyNgxGoogleAnalyticsComponent,View_EasyNgxGoogleAnalyticsComponent_Host_0,
    {config:'config'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NoYXJ1a2FobWVkbWF6dW1kZXIvRG9jdW1lbnRzL0dpdEh1Yi9jYXN0L2Vhc3ktbmd4LWdvb2dsZS1hbmFseXRpY3Mvc3JjL2Vhc3ktbmd4LWdvb2dsZS1hbmFseXRpY3MuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NoYXJ1a2FobWVkbWF6dW1kZXIvRG9jdW1lbnRzL0dpdEh1Yi9jYXN0L2Vhc3ktbmd4LWdvb2dsZS1hbmFseXRpY3Mvc3JjL2Vhc3ktbmd4LWdvb2dsZS1hbmFseXRpY3MuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvc2hhcnVrYWhtZWRtYXp1bWRlci9Eb2N1bWVudHMvR2l0SHViL2Nhc3QvZWFzeS1uZ3gtZ29vZ2xlLWFuYWx5dGljcy9zcmMvZWFzeS1uZ3gtZ29vZ2xlLWFuYWx5dGljcy5jb21wb25lbnQudHMuRWFzeU5neEdvb2dsZUFuYWx5dGljc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxlYXN5LW5neC1nb29nbGUtYW5hbHl0aWNzPjwvZWFzeS1uZ3gtZ29vZ2xlLWFuYWx5dGljcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtnREFBQSxVQUFBO3lDQUFBOzs7OzsifQ==
